### ISSUE TITLE
Add 'INSA Hauts de France' assets

### ISSUE THREAD

**Issue by SHAfoin** [SkytAsul/INSA-Typst-Template#1]
Hello,

I'm a student at INSA HdF and when I was looking at some typst template for my internship report and I saw yours for INSA Rennes.
I really liked it and I customized it by adding my school assets for the report.
I saw that you allow to create an issue for other INSA to bring their assets.
That's exactly what I did on a fork, and I also added an attribute to your template so you can choose which INSA use for the report.
I was wondering if you would like a pull request to add it to your repo ? If it's not an infrigement of your license of course.

**Comment by SkytAsul** [comment]
Hey, sure you can create a PR I'll gladly merge it!
