### ISSUE TITLE
Add INSA CVL assets

### ISSUE THREAD

**Issue by Jeomhps** [SkytAsul/INSA-Typst-Template#3]
Hi,

Like SHAfoin, I’m currently a student, though I’m studying at INSA CVL. I wanted to reach out because I also really like the Typst template you've created, and I’m considering adding some INSA CVL assets to the repository.

At the moment, I’ve only managed to obtain the classic front page assets, but I’m still missing a few key elements, such as the dark mode and colorful versions, as well as the back pages. Since these missing assets could break the package—causing calls to non-existent resources—I’ll be holding off until I receive a response from the communications service regarding access to these materials.

In the meantime, I wanted to know if you would be interested in having these assets added via merge request once I’ve gathered them all. Let me know what you think!

**Comment by SkytAsul** [comment]
Sure, I'm looking forward to your completed PR!

**Comment by Jeomhps** [comment]
Here you can found the PR associated to this issue : https://github.com/SkytAsul/INSA-Typst-Template/pull/4
